# Generated by Django 4.1.4 on 2022-12-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
