# Generated by Django 4.1.4 on 2022-12-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_profile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='profile',
            new_name='user',
        ),
    ]
