# Generated by Django 4.1.4 on 2022-12-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_user_followed_followrelation_followed_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrelation',
            options={'ordering': ['-followed_at']},
        ),
        migrations.RenameField(
            model_name='followrelation',
            old_name='date_followed',
            new_name='followed_at',
        ),
    ]
