# Generated by Django 4.1.4 on 2022-12-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_postcomment_post_postvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postvote',
            old_name='status',
            new_name='type',
        ),
    ]
